"  begun building my own .vimrc from this minimalistic one in Jan 2014 /David Engdal
" 
" minimal vimrc for new vim users to start with.
"
" Referenced here:
" http://vimuniversity.com/samples/your-first-vimrc-should-be-nearly-empty
"
" Original Author:	 Bram Moolenaar <Bram@vim.org>
" Made more minimal by:  Ben Orenstein
" Last change:	         2012 Jan 20
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"
"  If you don't understand a setting in here, just type ':h setting'.

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" setup Pathogen to manage plugins
filetype off                  " force reloading after pathogen loaded
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#incubate()
call pathogen#helptags()

" Make backspace behave in a sane manner.
set backspace=indent,eol,start

" Switch syntax highlighting on
syntax on

" Enable file type detection and do language-dependent indenting.
filetype plugin indent on

" To copy to and from clipboard: (seems to work anyway)
"set clipboard+=unnamed  " use the clipboards of vim and win
"set clipboard+=unnamedplus " use the clipboards of vim and X
"set go+=a               " Visual selection automatically copied to the clipboard
"set guioptions+=a
" ESC is too far away - and Steve Losh and Thanassis Tsiodras is right, this is better than jj
inoremap jk <esc>

" tags and autochdir for effichient tags usage
set tags=./tags,tags;
set autochdir
set tags+=/usr/include/tags
set tags+=/opt/tags

" For indentation without tabs:
set expandtab
set shiftwidth=4
set softtabstop=4

" Color schemes, e.g. slate, dessert, or evening
"set t_Co=256
set background=dark
colorscheme slate
"hi normal   ctermfg=black  ctermbg=white
highlight Normal ctermfg=grey ctermbg=black

" Nerdtree toggle
nmap <silent> <C-N> :NERDTreeToggle<CR>

" clang_complete
" path for osx:
"let g:clang_library_path = '/Developer/usr/clang-ide/lib'
" for Ubuntu:
let g:clang_library_path = '/usr/lib'
let g:clang_use_library = 1
" Avoid freezing on offending code
let g:clang_user_options='|| exit 0'
let g:clang_close_preview=1
